// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAalTJPAUBfC1YQMhoXBSka4pjX-D0Zk6c',
    appId: '1:902656895968:web:58a073aac1a77658f01985',
    messagingSenderId: '902656895968',
    projectId: 'todoapp-5503b',
    authDomain: 'todoapp-5503b.firebaseapp.com',
    storageBucket: 'todoapp-5503b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcyqai9GGj_dsNycN-PmidUx0AUeT-n6I',
    appId: '1:902656895968:android:c619f5216cfa5890f01985',
    messagingSenderId: '902656895968',
    projectId: 'todoapp-5503b',
    storageBucket: 'todoapp-5503b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDJbCHimZNhuCJEPH0VaT1L_Pn2BxluUM',
    appId: '1:902656895968:ios:661c8e559bbcc9f5f01985',
    messagingSenderId: '902656895968',
    projectId: 'todoapp-5503b',
    storageBucket: 'todoapp-5503b.appspot.com',
    iosBundleId: 'com.example.heritHomes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDJbCHimZNhuCJEPH0VaT1L_Pn2BxluUM',
    appId: '1:902656895968:ios:661c8e559bbcc9f5f01985',
    messagingSenderId: '902656895968',
    projectId: 'todoapp-5503b',
    storageBucket: 'todoapp-5503b.appspot.com',
    iosBundleId: 'com.example.heritHomes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAalTJPAUBfC1YQMhoXBSka4pjX-D0Zk6c',
    appId: '1:902656895968:web:58a073aac1a77658f01985',
    messagingSenderId: '902656895968',
    projectId: 'todoapp-5503b',
    authDomain: 'todoapp-5503b.firebaseapp.com',
    storageBucket: 'todoapp-5503b.appspot.com',
  );

}